### ISSUE TITLE
Remove the inline CSS

### ISSUE THREAD

**Issue by sk9331657** [NJACKWinterOfCode/Alphynite#1]
**I'm submitting a ...**
- [x] feature request

**Expected behaviour:**

Move the inline styling to external css.

**Would you like to work on the issue?**

No, open fo claiming.

**Comment by nikhils4** [comment]
Okay, I am new to the Github working I would be giving the steps I would be following, if i am wrong please correct me : 
1) Fork the repo and commit the changes to that
2) Test it and give a pull request to the this main repo

Is that fine ??

**Comment by sk9331657** [comment]
> Okay, I am new to the Github working I would be giving the steps I would be following, if i am wrong please correct me :
> 
> 1. Fork the repo and commit the changes to that
> 2. Test it and give a pull request to the this main repo
> 
> Is that fine ??

Yup fork and clone to your local computer. 
Commit changes and pull changes to your forked repo.
Create a pull request to main repo.

**Comment by nikhils4** [comment]
Got it, if any problem arises will back to you on repo's gitter channel.

**Comment by stephen1401** [comment]
Hey Can I claim this issue ?

**Comment by sk9331657** [comment]
@nikhils4  Are u working on this issue??

**Comment by nikhils4** [comment]
Yeah, will get back to you by 1 Dec on this. Exams are going on right now.

**Comment by stephen1401** [comment]
1 Dec over lemme work on it ?

**Comment by sk9331657** [comment]
@stephen1401  You can work on this issue #15  .

**Comment by sk9331657** [comment]
@nikhils4  Updates ?? If you are working on it dedicatedly, I will assign you this. Please report your status.

**Comment by nikhils4** [comment]
Yup already working on this alongwith Facebook and Gmail login integration one, as soon as i am done from my side i will give a pull request

> @nikhils4 Updates ?? If you are working on it dedicatedly, I will assign you this. Please report your status.

**Comment by ritwizsinha** [comment]
please assign me this issue i have almost competed work on it

**Comment by sk9331657** [comment]
@nikhils4  Updates?? @ritwizsinha  is already working on it.
