### ISSUE TITLE
Make project Live - Priority  Extremely High 

### ISSUE THREAD

**Issue by sk9331657** [NJACKWinterOfCode/Alphynite#15]
**I'm submitting a ...**
- [x] feature request

**Current behavior:**

No Deployments.
**Expected behavior:**

Deploy the project to Heroku or any other free hosting provider. 
Here is the resource for Heroku .
https://medium.com/@hellotunmbi/how-to-deploy-angular-application-to-heroku-1d56e09c5147

**Would you like to work on the issue?**

No.Open for others.

**Comment by aniket1897** [comment]
@sk9331657 I would like to work on this issue

**Comment by sk9331657** [comment]
@aniket1897  Use Cli because there is not automatic deployment.

**Comment by aniket1897** [comment]
Ok @sk9331657

**Comment by aniket1897** [comment]
Yes @sk9331657 I have referred it. If u see the code ```package.json``` file consists of both angular and node configs

**Comment by sk9331657** [comment]
> Yes @sk9331657 I have referred it. If u see the code `package.json` file consists of both angular and node configs

Yes, you need to add post script which compiles the angular code.

**Comment by aniket1897** [comment]
I have found a solution which says create a root package.json file and add the  ```postinstall``` script
Link : https://github.com/heroku/heroku-buildpack-nodejs/issues/385#issuecomment-291084067

**Comment by sk9331657** [comment]
{
  "name": "demo-deploy",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "node server.js",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ng build  --prod"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/cli": "^1.4.9",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/compiler-cli": "^4.4.6",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "express": "^4.16.2",
    "rxjs": "^5.4.2",
    "typescript": "~2.3.3",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.9",
    "@angular/compiler-cli": "^4.4.6",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "enhanced-resolve": "^3.3.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  },
  "engines": {
    "node": "6.11.0",
    "npm": "3.10.10"
  }
}

**Comment by sk9331657** [comment]
@aniket1897  Update ??

**Comment by aniket1897** [comment]
@sk9331657 Still not done. I'm trying

**Comment by sk9331657** [comment]
@aniket1897  Ok .

**Comment by aniket1897** [comment]
> I have found a solution which says create a root package.json file and add the `postinstall` script
> Link : [heroku/heroku-buildpack-nodejs#385 (comment)](https://github.com/heroku/heroku-buildpack-nodejs/issues/385#issuecomment-291084067)
@sk9331657 I tried using this method the application was deployed but front end of app is not getting displayed
