### ISSUE TITLE
Where's the frontend & backend folder? I can't find it.

### ISSUE THREAD

**Issue by bhaskarSingh** [NJACKWinterOfCode/Alphynite#19]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request

**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

**Comment by sk9331657** [comment]
@bhaskarSingh We have just updated codebase for deployment. Readme is now updated.
