### ISSUE TITLE
Redesign the HomePage 

### ISSUE THREAD

**Issue by sk9331657** [NJACKWinterOfCode/Alphynite#2]
**I'm submitting a ...**
- [x] feature request

**Current behaviour:**

The Ui of homepage is not upto mark.
**Expected behaviour:**

Suggest new UI design for home page.

**Comment by Sai-Adarsh** [comment]
Can i claim this issue and go ahead ?

**Comment by sk9331657** [comment]
You can work on issue but we will accept the pr after 1 dec . Instead make pr on github.com/sk9331657/Alphynite.

**Comment by sk9331657** [comment]
@Sai-Adarsh  Updates??

**Comment by pm-sharma** [comment]
I would like to work on this, shall I go ahead ??

**Comment by ritwizsinha** [comment]
can i work on this issue

**Comment by rustagishubhi** [comment]
Can I work on this issue?

**Comment by sk9331657** [comment]
@rustagishubhi  You can work on new issues as this one is completed.
