### ISSUE TITLE
Connect the Front End with Back End #4

### ISSUE THREAD

**Issue by sk9331657** [NJACKWinterOfCode/Alphynite#4]
**I'm submitting a ...**
- [x] bug report

**Would you like to work on the issue?**

No, Open for all.

**Comment by pm-sharma** [comment]
Shall I work on this?

**Comment by sk9331657** [comment]
Yup

**Comment by sk9331657** [comment]
Just make connections to store data in mongod .

**Comment by sk9331657** [comment]
@pm-sharma  Updates??

**Comment by pm-sharma** [comment]
Yup I am working on it as soon I am done I will give a pull request.

**Comment by sk9331657** [comment]
@pm-sharma This issue is already implemented, I just noticed that. You can work on another issue. Hope you don't mind it. Even issue hasn't been stated properly.
