### ISSUE TITLE
Connecting Backend with Mongod

### ISSUE THREAD

**Issue by championpaddler** [NJACKWinterOfCode/Alphynite#8]
**I'm submitting a ...**
- [x] feature request

**Expected behaviour:**

Connecting Backend with mongod and storing incoming data in mongod from api's.

**Comment by sk9331657** [comment]
@moulikcipherX  Updates ?? Are u working on it??

**Comment by moulikcipherX** [comment]
Yeah, I am working on it stuck due to my exams for a day.

**Comment by sk9331657** [comment]
@moulikcipherX  Ok

**Comment by aniket1897** [comment]
@sk9331657 I would like to work on this issue if @moulikcipherX is not working.

**Comment by sk9331657** [comment]
@moulikcipherX  Update??

**Comment by sk9331657** [comment]
@moulikcipherX  I am assigning this to @aniket1897  as you are fixing your previous issue.

**Comment by aniket1897** [comment]
@sk9331657 I am storing details of user from signup page should I store all details such as encrypted password?
